apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api-platform.fullname" . }}
  labels:
    {{- include "api-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  database-url: {{ printf "pgsql://%s:%s@%s-postgresql/%s?serverVersion=13&charset=utf8" .Values.postgresql.postgresqlUsername .Values.postgresql.postgresqlPassword .Release.Name .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  {{- else }}
  database-url: {{ .Values.postgresql.url | b64enc | quote }}
  {{- end }}
  php-app-secret: {{ .Values.php.appSecret | default (randAlphaNum 40) | b64enc | quote }}
  mercure-jwt-token: {{ .Values.mercure.jwtToken | b64enc | quote }}
  mercure-publisher-jwt-key: {{ .Values.mercure.publisherJwtKey | b64enc | quote }}
  mercure-subscriber-jwt-key: {{ .Values.mercure.subscriberJwtKey | b64enc | quote }}
